#!/bin/bash

# Get the C file name from the $CFILE variable
c_file="$CFILE"

# Replace the .c extension with .s
s_file="${c_file%.c}.s"

# Generate the assembly code using gcc
gcc -S -masm=intel "$c_file" -o "$s_file"
